const medicalConsultConstants = {
  SET_AREA_LIST: "SET_AREA_LIST",
  CHECK_AREA_LIST: "CHECK_AREA_LIST",
  UPDATE_CONSULT_CONTENT: "UPDATE_CONSULT_CONTENT",
  UPDATE_AREA_LIST: "UPDATE_AREA_LIST",
  SET_MEDICAL_CONSULT_ATTR_VALUE: "SET_MEDICAL_CONSULT_ATTR_VALUE"
};

export default medicalConsultConstants;
